### ISSUE TITLE
slides 6 to 9

### ISSUE THREAD

**Issue by lgatto** [lmsimp/2018_EuroBioc_Breckels#2]
What is the aim of slides 6 to 9? They seem to be a summary and redundant with slides 11 to 17 (that should be demonstrated interactively).

**Comment by lmsimp** [comment]
They are just there as a reminder/placeholder/prompt to open each app interactively.

Same with slides 11-17.  Just thought I’d add these as reminders. Delete as you feel. 

See also demo.R which contains the same information and notes for when opening and demonstrating the apps.
